const { initDatabase, run, get } = require('./database/db');

async function seedSierraLeoneCatalog() {
  await initDatabase();

  // Clear non-realistic cars and seed popular Sierra Leone vehicles
  run("DELETE FROM vehicles");

  const slVehicles = [
    [
      'Toyota Land Cruiser V8 VXR (300 Series)',
      'Toyota',
      'Land Cruiser VXR 3.5L Twin-Turbo',
      2024,
      3800000,
      1200,
      'Petrol',
      '409 hp',
      '3.5L V6 Twin-Turbo',
      'Automatic 10-spd',
      'SUV',
      'Pearl White',
      'Freetown',
      'new',
      'available',
      1,
      'The ultimate status luxury 4x4 in Sierra Leone. Full option VXR trim, beige leather, sunroof, 360 camera, JBL audio system, Crawl Control, multi-terrain select.',
      JSON.stringify(['https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=900&q=85'])
    ],
    [
      'Lexus LX 600 VIP Executive',
      'Lexus',
      'LX 600 VIP 4-Seater',
      2024,
      4500000,
      450,
      'Petrol',
      '409 hp',
      '3.5L V6 Twin-Turbo',
      'Automatic 10-spd',
      'SUV',
      'Onyx Black',
      'Freetown',
      'new',
      'available',
      1,
      'Prestige executive luxury SUV. VIP rear lounge seats with massage, Mark Levinson 25-speaker sound system, hydraulic suspension, dual rear entertainment displays.',
      JSON.stringify(['https://images.unsplash.com/photo-1563720223185-11003d516935?w=900&q=85'])
    ],
    [
      'Toyota Land Cruiser Prado TX-L',
      'Toyota',
      'Prado TX-L 2.8L Turbo Diesel',
      2024,
      1850000,
      0,
      'Diesel',
      '201 hp',
      '2.8L Turbo Diesel',
      'Automatic 6-spd',
      'SUV',
      'Silver Metallic',
      'Freetown',
      'new',
      'available',
      1,
      'Sierra Leone\'s favorite executive 7-seater SUV. Leather interior, cool box, side steps, roof rails, push start, dual-zone climate control.',
      JSON.stringify(['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=900&q=85'])
    ],
    [
      'Mercedes-AMG G 63 (G-Wagon)',
      'Mercedes-Benz',
      'G 63 AMG V8 Biturbo',
      2023,
      5200000,
      3500,
      'Petrol',
      '585 hp',
      '4.0L V8 Biturbo',
      'AMG SPEEDSHIFT 9G',
      'SUV',
      'Obsidian Black',
      'Freetown',
      'used',
      'available',
      1,
      'Iconic luxury G-Wagon in Freetown. Nappa leather interior, Burmester surround sound, AMG performance exhaust, 22-inch forged AMG wheels.',
      JSON.stringify(['https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?w=900&q=85'])
    ],
    [
      'Range Rover Autobiography P530',
      'Land Rover',
      'Range Rover Autobiography V8',
      2024,
      4900000,
      800,
      'Petrol',
      '530 hp',
      '4.4L V8 Twin-Turbo',
      'Automatic 8-spd',
      'SUV',
      'Batumi Gold',
      'Freetown',
      'new',
      'available',
      0,
      'Top-tier flagship luxury SUV. Semi-Aniline leather seats, executive class rear seating, Meridian Signature sound, digital LED headlights.',
      JSON.stringify(['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=900&q=85'])
    ],
    [
      'Toyota Hilux GR Sport Double Cab',
      'Toyota',
      'Hilux GR Sport 2.8 D-4D',
      2024,
      1350000,
      0,
      'Diesel',
      '221 hp',
      '2.8L Turbo Diesel',
      'Automatic 6-spd',
      'Pickup',
      'Emotional Red',
      'Bo',
      'new',
      'available',
      0,
      'Heavy-duty luxury pickup built for Sierra Leone terrain. KYB Monotube shock absorbers, GR suede/leather seats, 18-inch black alloy wheels, roller shutter.',
      JSON.stringify(['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&q=85'])
    ],
    [
      'Nissan Patrol V8 Titanium',
      'Nissan',
      'Patrol V8 5.6L Titanium',
      2023,
      2650000,
      4200,
      'Petrol',
      '400 hp',
      '5.6L V8 NA',
      'Automatic 7-spd',
      'SUV',
      'Hermosa Blue',
      'Freetown',
      'used',
      'available',
      0,
      'King of the off-road in West Africa. Tan leather interior, Bose 13-speaker audio, hydraulic body motion control, dual 8-inch rear screens.',
      JSON.stringify(['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=900&q=85'])
    ],
    [
      'Lexus RX 350 Luxury AWD',
      'Lexus',
      'RX 350 Luxury 2.4L Turbo',
      2024,
      1950000,
      0,
      'Petrol',
      '275 hp',
      '2.4L Turbo Inline-4',
      'Automatic 8-spd',
      'SUV',
      'Sonic Titanium',
      'Freetown',
      'new',
      'available',
      0,
      'Elegant executive crossover. Semi-aniline leather, 14-inch touchscreen, panoramic glass roof, head-up display, wireless Apple CarPlay.',
      JSON.stringify(['https://images.unsplash.com/photo-1563720223185-11003d516935?w=900&q=85'])
    ],
    [
      'Hyundai Santa Fe Calligraphy',
      'Hyundai',
      'Santa Fe Calligraphy 2.5T AWD',
      2024,
      1250000,
      0,
      'Petrol',
      '277 hp',
      '2.5L Turbo Inline-4',
      'DCT 8-spd',
      'SUV',
      'Terracotta Orange',
      'Freetown',
      'new',
      'available',
      0,
      'Modern 7-seater executive SUV. Nappa leather, dual wireless charging pads, Bose audio, remote smart parking assist, UV-C sterilization compartment.',
      JSON.stringify(['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=900&q=85'])
    ],
    [
      'Mercedes-Benz GLE 450 4MATIC',
      'Mercedes-Benz',
      'GLE 450 AMG Line 3.0L EQ Boost',
      2023,
      2450000,
      6100,
      'Hybrid',
      '362 hp',
      '3.0L Inline-6 Turbo + EQ Boost',
      '9G-TRONIC',
      'SUV',
      'Emerald Green',
      'Freetown',
      'used',
      'available',
      0,
      'Executive luxury SUV. MBUX widescreen cockpit, Burmester sound, AIRMATIC air suspension, panoramic sliding sunroof.',
      JSON.stringify(['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&q=85'])
    ],
    [
      'Kia Sportage GT-Line AWD',
      'Kia',
      'Sportage GT-Line 1.6T',
      2024,
      890000,
      0,
      'Petrol',
      '177 hp',
      '1.6L Turbo Inline-4',
      'DCT 7-spd',
      'SUV',
      'Wolf Grey',
      'Makeni',
      'new',
      'available',
      0,
      'Popular compact luxury crossover. Curved dual 12.3-inch displays, Harman Kardon premium sound, panoramic sunroof, ambient lighting.',
      JSON.stringify(['https://images.unsplash.com/photo-1541348263662-e082662d82da?w=900&q=85'])
    ],
    [
      'Land Rover Defender 110 SE',
      'Land Rover',
      'Defender 110 SE D300',
      2023,
      2950000,
      4800,
      'Diesel',
      '300 hp',
      '3.0L Inline-6 Turbo Diesel',
      'Automatic 8-spd',
      'SUV',
      'Pangea Green',
      'Freetown',
      'used',
      'available',
      0,
      'All-terrain luxury off-roader. Ebony Grained leather, air suspension, ClearSight rear-view mirror, Meridian sound, 3D surround camera.',
      JSON.stringify(['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&q=85'])
    ]
  ];

  for (const v of slVehicles) {
    run(`
      INSERT INTO vehicles
        (title,brand,model,year,price,mileage,fuel,hp,engine,transmission,body,colour,location,condition_type,status,featured,description,images,video_url,updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'',datetime('now'))
    `, v);
  }

  console.log('✅  Successfully updated catalog to popular Sierra Leone luxury & executive vehicles!');
}

seedSierraLeoneCatalog().catch(console.error);
